//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScooterRentalApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int RentID { get; set; }
        public int CustomerID { get; set; }
        public int ScooterID { get; set; }
        public System.DateTime DateRented { get; set; }
        public Nullable<bool> IsReturned { get; set; }
        public Nullable<System.DateTime> DateOfReturn { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Scooter Scooter { get; set; }
    }
}
